/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EvaAdminUsuarios { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idusuario: string;
    /**
     * Note: This is a Foreign Key to `eva_usuario_roles.idrol`.<fk table='eva_usuario_roles' column='idrol'/>
     */
    idrol?: number;
    fecharegistro?: string;
}
