/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EvaPreguntaConfigs { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idconfiguracion: number;
    idpregunta: number;
    /**
     * Note: This is a Foreign Key to `eva_pregunta_estruct.idestructura`.<fk table='eva_pregunta_estruct' column='idestructura'/>
     */
    idestructura: number;
    sumpuntoxrespuesta: string;
    esobligatoria?: string;
    dsctoxnoresponder?: number;
}
