/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EvaPreguntas { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idpregunta: number;
    /**
     * Note: This is a Foreign Key to `eva_categorias.idexamen`.<fk table='eva_categorias' column='idexamen'/>
     */
    idexamen?: number;
    /**
     * Note: This is a Foreign Key to `eva_pregunta_configs.idconfiguracion`.<fk table='eva_pregunta_configs' column='idconfiguracion'/>
     */
    idconfiguracion: number;
    /**
     * Note: This is a Foreign Key to `eva_categorias.catcodigoexterno`.<fk table='eva_categorias' column='catcodigoexterno'/>
     */
    catcodigoexterno?: string;
    pregunta?: string;
    descripcion?: string;
    puntaje?: number;
    /**
     * Note: This is a Foreign Key to `eva_estados.idestado`.<fk table='eva_estados' column='idestado'/>
     */
    idestado: number;
    /**
     * Note: This is a Foreign Key to `eva_admin_usuarios.idusuario`.<fk table='eva_admin_usuarios' column='idusuario'/>
     */
    idautor?: string;
    imagenurl?: string;
    fecharegistro?: string;
}
