/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EvaUsuarioRoles { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idrol: number;
    nombre?: string;
    /**
     * Note: This is a Foreign Key to `eva_estados.idestado`.<fk table='eva_estados' column='idestado'/>
     */
    idestado?: number;
    fecharegistro?: string;
}
