export * from './evaAdminUsuarios.service';
import { EvaAdminUsuariosService } from './evaAdminUsuarios.service';
export * from './evaCategorias.service';
import { EvaCategoriasService } from './evaCategorias.service';
export * from './evaEstados.service';
import { EvaEstadosService } from './evaEstados.service';
export * from './evaExamenUsuarios.service';
import { EvaExamenUsuariosService } from './evaExamenUsuarios.service';
export * from './evaExamenes.service';
import { EvaExamenesService } from './evaExamenes.service';
export * from './evaLogins.service';
import { EvaLoginsService } from './evaLogins.service';
export * from './evaPreguntaAlternativas.service';
import { EvaPreguntaAlternativasService } from './evaPreguntaAlternativas.service';
export * from './evaPreguntaConfigs.service';
import { EvaPreguntaConfigsService } from './evaPreguntaConfigs.service';
export * from './evaPreguntaEstruct.service';
import { EvaPreguntaEstructService } from './evaPreguntaEstruct.service';
export * from './evaPreguntas.service';
import { EvaPreguntasService } from './evaPreguntas.service';
export * from './evaResoluciones.service';
import { EvaResolucionesService } from './evaResoluciones.service';
export * from './evaUsuarioRoles.service';
import { EvaUsuarioRolesService } from './evaUsuarioRoles.service';
export * from './introspection.service';
import { IntrospectionService } from './introspection.service';
export const APIS = [EvaAdminUsuariosService, EvaCategoriasService, EvaEstadosService, EvaExamenUsuariosService, EvaExamenesService, EvaLoginsService, EvaPreguntaAlternativasService, EvaPreguntaConfigsService, EvaPreguntaEstructService, EvaPreguntasService, EvaResolucionesService, EvaUsuarioRolesService, IntrospectionService];
